### ISSUE TITLE
Multiple versions of the pipeline currently active

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/SomaticAmplicon#15]
There are currently three different versions of this pipeline active
- v1.7.6 for BRCA GeneRead
- v1.7.7 for CRM (same as v1.7.6 with virtual hood & custom coverage reporting)
- v1.7.8 for TruSightMyeloid (same as v1.7.6 with newer version of VEP)

This is really confusing to maintain - we need to combine these into one pipeline, with optional loops for any panel specific steps

**Comment by erikwaskiewicz** [comment]
BRCA GeneRead and TruSightMyeloid now both being run on v1.8.1

CRM now being run on v1.7.9

**Comment by josephhalstead** [comment]
closed by pull request #34
