### ISSUE TITLE
Annotation updates for next version

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/SomaticAmplicon#33]
As part of an audit into the annotation sources in this pipeline, these tools should be updated on the next major version. These will be implemented as part of the change over to running the pipeline on Wren.

- VEP from v86/v97 to v102 - this will fix issue #15 
- bed2hgvs to new Wren version that doesn't require Mutalyzer
- FOCUS4 and CRM poly lists to be reviewed and updated

See Q-pulse audit GEN-20-543 for full details

**Comment by josephhalstead** [comment]
closed by pull request #34
